package vista;

import entities.Usuario;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;
import view_controller.CreateGroupController;

public class CreateGroupView extends javax.swing.JFrame
{
    // Aun falta configurar antes de entrar a esta view para reiniciar los datos de la lista
    
    public CreateGroupView()
    {
        initComponents();
        users = new ArrayList< Usuario > ();
        desplegarDatos();
        controlador = new CreateGroupController( this );
        addMemberBtn.addActionListener( controlador );
        addGroupBtn.addActionListener( controlador );
        deleteMemberBtn.addActionListener( controlador );
    }
    
    public void desplegarDatos()
    {
        String[] columnas = {"Name" , "Email" , "Mobile"};
        Object[][] data = new Object[users.size()][columnas.length];
        for( int i = 0 ; i < users.size() ; ++i )
        {
            data[i][0] = users.get(i).getName();
            data[i][1] = users.get(i).getEmail();
            data[i][2] = users.get(i).getMobile();
        }
        DefaultTableModel model = new DefaultTableModel( data , columnas );
        membersTable.setModel( model );
        membersScrollPane.setViewportView( membersTable );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_fondo = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        groupNameField = new javax.swing.JTextField();
        membersPanel = new javax.swing.JPanel();
        membersScrollPane = new javax.swing.JScrollPane();
        membersTable = new javax.swing.JTable();
        addGroupBtn = new javax.swing.JButton();
        addMemberBtn = new javax.swing.JButton();
        deleteMemberBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloLabel.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        tituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLabel.setText("Create Group");

        nombreLabel.setText("Group Name");

        groupNameField.setText("jTextField1");

        membersPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Members"));
        membersPanel.setToolTipText("");
        membersPanel.setName(""); // NOI18N

        membersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        membersScrollPane.setViewportView(membersTable);

        javax.swing.GroupLayout membersPanelLayout = new javax.swing.GroupLayout(membersPanel);
        membersPanel.setLayout(membersPanelLayout);
        membersPanelLayout.setHorizontalGroup(
            membersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(membersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(membersScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
                .addContainerGap())
        );
        membersPanelLayout.setVerticalGroup(
            membersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(membersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(membersScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addContainerGap())
        );

        addGroupBtn.setText("Add Group");
        addGroupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGroupBtnActionPerformed(evt);
            }
        });

        addMemberBtn.setText("Add Member");
        addMemberBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMemberBtnActionPerformed(evt);
            }
        });

        deleteMemberBtn.setText("Delete member");

        javax.swing.GroupLayout Panel_fondoLayout = new javax.swing.GroupLayout(Panel_fondo);
        Panel_fondo.setLayout(Panel_fondoLayout);
        Panel_fondoLayout.setHorizontalGroup(
            Panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_fondoLayout.createSequentialGroup()
                .addGroup(Panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_fondoLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(Panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Panel_fondoLayout.createSequentialGroup()
                                .addComponent(nombreLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(groupNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(374, 374, 374))
                            .addComponent(membersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Panel_fondoLayout.createSequentialGroup()
                                .addComponent(addMemberBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteMemberBtn))))
                    .addGroup(Panel_fondoLayout.createSequentialGroup()
                        .addGap(375, 375, 375)
                        .addComponent(addGroupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        Panel_fondoLayout.setVerticalGroup(
            Panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_fondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tituloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(groupNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMemberBtn)
                    .addComponent(deleteMemberBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(membersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addGroupBtn)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addGroupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGroupBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addGroupBtnActionPerformed

    private void addMemberBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMemberBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addMemberBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_fondo;
    private javax.swing.JButton addGroupBtn;
    private javax.swing.JButton addMemberBtn;
    private javax.swing.JButton deleteMemberBtn;
    private javax.swing.JTextField groupNameField;
    private javax.swing.JPanel membersPanel;
    private javax.swing.JScrollPane membersScrollPane;
    private javax.swing.JTable membersTable;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
    private CreateGroupController controlador;
    private List < Usuario > users;
    
    public List < Usuario > getUser_list()
    {
        return users;
    }

    public javax.swing.JTable getMembersTable()
    {
        return membersTable;
    }
    
    public javax.swing.JTextField getGroupNameField()
    {
        return groupNameField;
    }
    
    public JButton getAddGroupBtn()
    {
        return addGroupBtn;
    }

    public JButton getDeleteMemberBtn()
    {
        return deleteMemberBtn;
    }
    
    public JButton getAddMemberBtn()
    {
        return addMemberBtn;
    }
    
    
    
}
