package vista;

import entities.Grupo;
import entities.Usuario;
import entities_controllers.Conexion;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import view_controller.ManageGroupController;

public class ManageGroupView extends javax.swing.JFrame
{
    
    private List < Usuario > usuarios_grupo;
    private List < Usuario > usuarios_eliminar;
    private ManageGroupController controller;
    private BigDecimal groupID;
    
    public ManageGroupView()
    {
        initComponents();
        usuarios_grupo = new ArrayList < Usuario >();
        usuarios_eliminar = new ArrayList < Usuario >();
        controller = new ManageGroupController(this);
        setGroupLeaderBtn.addActionListener(controller);
        deleteGroupBtn.addActionListener(controller);
        desplegarDatos();
    }
    
    // Only call this method if you already set a groupID
    public void init()
    {
        controller.init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        manageGroupTitle = new javax.swing.JLabel();
        users_scrollPane = new javax.swing.JScrollPane();
        users_table = new javax.swing.JTable();
        deleteGroupBtn = new javax.swing.JButton();
        setGroupLeaderBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        manageGroupTitle.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        manageGroupTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageGroupTitle.setText("Manage group");

        users_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Select", "Name", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        users_scrollPane.setViewportView(users_table);

        deleteGroupBtn.setText("Delete selected from group");

        setGroupLeaderBtn.setText("Set as group leader");
        setGroupLeaderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setGroupLeaderBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(manageGroupTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(deleteGroupBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(setGroupLeaderBtn))
                    .addComponent(users_scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(manageGroupTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(users_scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteGroupBtn)
                    .addComponent(setGroupLeaderBtn))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setGroupLeaderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setGroupLeaderBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setGroupLeaderBtnActionPerformed
    
    public void desplegarDatos()
    {
        DefaultTableModel model = ( DefaultTableModel )users_table.getModel();
        for (int i = model.getRowCount() - 1 ; i >= 0 ; --i )
            model.removeRow(i);
        for( int i = 0 ; i < usuarios_grupo.size() ; ++i )
        {
            //if( usuarios_grupo.get(i).getEmail().equals( MainView.getActual_user().getEmail() ) )   continue;
            model.addRow( new Object[] { false , usuarios_grupo.get(i).getName() , usuarios_grupo.get(i).getEmail() } );
        }
        users_table.setModel( model );
        users_scrollPane.setViewportView( users_table );
    }
    
    public BigDecimal getGroupID()
    {
        return groupID;
    }
    
    public void setGroupID( BigDecimal nuevo )
    {
        groupID = nuevo;
    }
    
    public javax.swing.JButton getDeleteGroupBtn()
    {
        return deleteGroupBtn;
    }
    
    public void setGroup_list_user( List < Usuario > lista )
    {
        usuarios_grupo = lista;
    }
    
    public List < Usuario > getGroup_list_user()
    {
        return usuarios_grupo;
    }
    
    public void setDelete_list_user( List < Usuario > lista )
    {
        usuarios_eliminar = lista;
    }
    
    public List < Usuario > getDelete_list_user()
    {
        return usuarios_eliminar;
    }
    
    public javax.swing.JButton getGroupLeaderBtn()
    {
        return setGroupLeaderBtn;
    }
    
    public javax.swing.JTable getUsers_table()
    {
        return users_table;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteGroupBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel manageGroupTitle;
    private javax.swing.JButton setGroupLeaderBtn;
    private javax.swing.JScrollPane users_scrollPane;
    private javax.swing.JTable users_table;
    // End of variables declaration//GEN-END:variables
}
