package vista;

import java.math.BigDecimal;
import view_controller.ViewGroupViewController;

public class ViewGroupView extends javax.swing.JFrame
{

    ViewGroupViewController controller;
    private BigDecimal groupID;
    
    public ViewGroupView()
    {
        initComponents();
        controller = new ViewGroupViewController(this);
        goBackBtn.addActionListener(controller);
        manageGroupBtn.addActionListener(controller);
        postBillBtn.addActionListener(controller);
        makeTransactionBtn.addActionListener(controller);
    }
    
    public void init()
    {
        controller.init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ViewGroupTitleLabel = new javax.swing.JLabel();
        membersScrollPane = new javax.swing.JScrollPane();
        membersTable = new javax.swing.JTable();
        groupNameLabel = new javax.swing.JLabel();
        groupNameTextField = new javax.swing.JTextField();
        goBackBtn = new javax.swing.JButton();
        manageGroupBtn = new javax.swing.JButton();
        postBillBtn = new javax.swing.JButton();
        makeTransactionBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ViewGroupTitleLabel.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        ViewGroupTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ViewGroupTitleLabel.setText("View Group");

        membersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        membersScrollPane.setViewportView(membersTable);

        groupNameLabel.setText("Group Name:");

        groupNameTextField.setEditable(false);
        groupNameTextField.setText("jTextField1");

        goBackBtn.setText("Go Back");

        manageGroupBtn.setText("Manage group");

        postBillBtn.setText("Post Bill");

        makeTransactionBtn.setText("Make Transaction");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewGroupTitleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(membersScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(groupNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(groupNameTextField))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(goBackBtn)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(manageGroupBtn)
                                .addGap(57, 57, 57)
                                .addComponent(postBillBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(makeTransactionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(goBackBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewGroupTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(groupNameLabel)
                    .addComponent(groupNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(membersScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageGroupBtn)
                    .addComponent(postBillBtn)
                    .addComponent(makeTransactionBtn))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ViewGroupTitleLabel;
    private javax.swing.JButton goBackBtn;
    private javax.swing.JLabel groupNameLabel;
    private javax.swing.JTextField groupNameTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton makeTransactionBtn;
    private javax.swing.JButton manageGroupBtn;
    private javax.swing.JScrollPane membersScrollPane;
    private javax.swing.JTable membersTable;
    private javax.swing.JButton postBillBtn;
    // End of variables declaration//GEN-END:variables

    public BigDecimal getGroupID()
    {
        return groupID;
    }
    public javax.swing.JTable getMembersTable()
    {
        return membersTable;
    }
    
    public void setGroupID( BigDecimal newGroupID )
    {
        groupID = newGroupID;
    }
    
    public javax.swing.JTextField getGroupNameTextField()
    {
        return groupNameTextField;
    }
    
    public javax.swing.JScrollPane getMembersScrollPane()
    {
        return membersScrollPane;
    }
    
    public javax.swing.JButton getBackBtn()
    {
        return goBackBtn;
    }
    
    public javax.swing.JButton getManageGroupBtn()
    {
        return manageGroupBtn;
    }
    
    public javax.swing.JButton getMakeTransactionBtn()
    {
        return makeTransactionBtn;
    }
    
    public javax.swing.JButton getPostBillBtn()
    {
        return postBillBtn;
    }
    
}
