WITH CONSULT AS (SELECT TO_CHAR(fecha,'DD/MM/YYYY') AS FECHA, AMOUNT, GRUPO.NAME
FROM BILL JOIN GRUPO ON BILL.ID_GROUP = GRUPO.ID
)

SELECT *
FROM CONSULT
PIVOT (SUM(AMOUNT) FOR (NAME) IN ('ola','test','el grupo de ivan :v'));
